### ISSUE TITLE
Plugin breaks code

### ISSUE THREAD

**Issue by alvaro-octal** [trivago/prettier-plugin-twig-melody#5]
Hi,

I've just tried the plugin on a file, here is my input:

```twig
{% set index = 0 %}

<!-- Pregunta 0: q -->

{% include 'pages/formularios/sub/pregunta.html' %}
{% set index = index + 1 %}

<div class="panel panel-default panel-pregunta">
    <div class="panel-body">
        <div class="striped-rows">

            <!-- Pregunta 1 -->

            {% include 'pages/formularios/sub/pregunta-simple.html' %}
            {% set index = index + 1 %}

            <!-- Pregunta 2 -->

            {% include 'pages/formularios/sub/pregunta-simple.html' %}
            {% set index = index + 1 %}

            <!-- Pregunta 3 -->

            {% include 'pages/formularios/sub/pregunta-simple.html' %}
            {% set index = index + 1 %}

            <!-- Pregunta 4 -->

            {% include 'pages/formularios/sub/pregunta-simple.html' %}
            {% set index = index + 1 %}
        </div>
    </div>
</div>

<!-- Pregunta 5 -->

{% include 'pages/formularios/sub/pregunta.html' %}
{% set index = index + 1 %}
```

By running:

```bash
prettier actividad-fisica.html.twig --write
```

It outputs:
```twig
{% set index = 0 %}<!-- Pregunta 0: q -->{% include 'pages/formularios/sub/pregunta.html' %}
{% set index = index + 1 %}

<div class="panel panel-default panel-pregunta">
  <div class="panel-body">
    <div class="striped-rows">
      <!-- Pregunta 1 -->{% include 'pages/formularios/sub/pregunta-simple.html' %}
      {% set {{ index }} = {{ index + 1 }} %}<!-- Pregunta 2 -->{% include 'pages/formularios/sub/pregunta-simple.html' %}
      {% set {{ index }} = {{ index + 1 }} %}<!-- Pregunta 3 -->{% include 'pages/formularios/sub/pregunta-simple.html' %}
      {% set {{ index }} = {{ index + 1 }} %}<!-- Pregunta 4 -->{% include 'pages/formularios/sub/pregunta-simple.html' %}
      {% set {{ index }} = {{ index + 1 }} %}
    </div>
  </div>
</div><!-- Pregunta 5 -->{% include 'pages/formularios/sub/pregunta.html' %}
{% set index = index + 1 %}
```

Note that `{% set {{ index }} = {{ index + 1 }} %}` is now broken code, and if you rerun the command it outputs:

```
[error] actividad-fisica.html.twig: Error: ERROR: Invalid Token
[error]    6 |     <div class="striped-rows">
[error]    7 |       <!-- Pregunta 1 -->{% include 'pages/formularios/sub/pregunta-simple.html' %}
[error] >  8 |       {% set {{ index }} = {{ index + 1 }} %}<!-- Pregunta 2 -->{% include 'pages/formularios/sub/pregunta-simple.html' %}
[error]      |              ^
[error]    9 |       {% set {{ index }} = {{ index + 1 }} %}<!-- Pregunta 3 -->{% include 'pages/formularios/sub/pregunta-simple.html' %}
[error]   10 |       {% set {{ index }} = {{ index + 1 }} %}<!-- Pregunta 4 -->{% include 'pages/formularios/sub/pregunta-simple.html' %}
[error]   11 |       {% set {{ index }} = {{ index + 1 }} %}
[error]
[error] Expected symbol but found { instead.
[error]     at TokenStream.error (C:\Users\Alvaro\AppData\Roaming\npm\node_modules\prettier-plugin-twig-melody\node_modules\melody-parser\lib\index.js:958:15)
[error]     at TokenStream.expect (C:\Users\Alvaro\AppData\Roaming\npm\node_modules\prettier-plugin-twig-melody\node_modules\melody-parser\lib\index.js:937:14)
[error]     at Object.parse (C:\Users\Alvaro\AppData\Roaming\npm\node_modules\prettier-plugin-twig-melody\node_modules\melody-extension-core\lib\index.js:1441:31)
[error]     at Parser.matchTag (C:\Users\Alvaro\AppData\Roaming\npm\node_modules\prettier-plugin-twig-melody\node_modules\melody-parser\lib\index.js:506:23)
[error]     at Parser.parse (C:\Users\Alvaro\AppData\Roaming\npm\node_modules\prettier-plugin-twig-melody\node_modules\melody-parser\lib\index.js:366:32)
[error]     at Parser.matchElement (C:\Users\Alvaro\AppData\Roaming\npm\node_modules\prettier-plugin-twig-melody\node_modules\melody-parser\lib\index.js:415:41)
[error]     at Parser.parse (C:\Users\Alvaro\AppData\Roaming\npm\node_modules\prettier-plugin-twig-melody\node_modules\melody-parser\lib\index.js:375:32)
[error]     at Parser.matchElement (C:\Users\Alvaro\AppData\Roaming\npm\node_modules\prettier-plugin-twig-melody\node_modules\melody-parser\lib\index.js:415:41)
[error]     at Parser.parse (C:\Users\Alvaro\AppData\Roaming\npm\node_modules\prettier-plugin-twig-melody\node_modules\melody-parser\lib\index.js:375:32)
[error]     at Parser.matchElement (C:\Users\Alvaro\AppData\Roaming\npm\node_modules\prettier-plugin-twig-melody\node_modules\melody-parser\lib\index.js:415:41)
[error]     at Parser.parse (C:\Users\Alvaro\AppData\Roaming\npm\node_modules\prettier-plugin-twig-melody\node_modules\melody-parser\lib\index.js:375:32)
[error]     at Object.parse (C:\Users\Alvaro\AppData\Roaming\npm\node_modules\prettier-plugin-twig-melody\src\parser.js:65:19)
[error]     at Object.parse$2 [as parse] (C:\Users\Alvaro\AppData\Roaming\npm\node_modules\prettier\bin-prettier.js:10631:19)
[error]     at coreFormat (C:\Users\Alvaro\AppData\Roaming\npm\node_modules\prettier\bin-prettier.js:13890:23)
[error]     at format (C:\Users\Alvaro\AppData\Roaming\npm\node_modules\prettier\bin-prettier.js:14148:73)
[error]     at formatWithCursor (C:\Users\Alvaro\AppData\Roaming\npm\node_modules\prettier\bin-prettier.js:14164:12)
```

**Comment by twbartel** [comment]
Hi Alvaro,

I just published v0.0.25 which should fix your issues.
Can you give it a try?

Cheers
Tom

**Comment by twbartel** [comment]
@alvaro-octal have you had a chance to try the new version yet?

**Comment by alvaro-octal** [comment]
Sorry for the delay, OK, now seems to be working fine. Closing issue.
